# Generated by Django 5.2.6 on 2025-09-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
