# Generated by Django 5.2.1 on 2025-10-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0004_alter_course_options_alter_presentation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='audio_duration',
            field=models.FloatField(blank=True, help_text='Duración del audio en segundos', null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='transcription_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='transcription_segments',
            field=models.JSONField(blank=True, help_text='Segmentos de transcripción con timestamps', null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='transcription_text',
            field=models.TextField(blank=True, help_text='Transcripción completa del video', null=True),
        ),
    ]
