# Generated by Django 5.2.7 on 2025-10-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0005_presentation_audio_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de análisis completo de IA', null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='participation_data',
            field=models.JSONField(blank=True, help_text='Datos de participación detectados mediante análisis de rostros (Persona 1, Persona 2, etc.)', null=True),
        ),
    ]
