# Generated by Django 5.2.7 on 2025-10-09 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0006_presentation_analyzed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='is_live_recording',
            field=models.BooleanField(default=False, help_text='Indica si el video fue grabado en vivo'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='liveness_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Confianza del análisis de liveness', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='presentation',
            name='liveness_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Score de liveness (0-100, mayor = más probable en vivo)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='presentation',
            name='recording_type',
            field=models.CharField(blank=True, choices=[('LIVE', 'En Vivo'), ('LIKELY_LIVE', 'Probablemente en Vivo'), ('LIKELY_RECORDED', 'Probablemente Pregrabado'), ('RECORDED', 'Pregrabado'), ('UNKNOWN', 'Desconocido')], help_text='Tipo de grabación detectado', max_length=20, null=True),
        ),
    ]
