# Generated by Django 5.2.7 on 2025-10-10 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0007_presentation_is_live_recording_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Persona 1, Persona 2, etc.', max_length=50, verbose_name='Etiqueta')),
                ('participation_time', models.FloatField(help_text='Tiempo total que estuvo visible/hablando', verbose_name='Tiempo de participación (segundos)')),
                ('time_percentage', models.FloatField(help_text='% del tiempo total de la exposición', verbose_name='Porcentaje de tiempo')),
                ('transcription', models.TextField(help_text='Texto transcrito de esta persona', verbose_name='Transcripción')),
                ('word_count', models.IntegerField(default=0, verbose_name='Cantidad de palabras')),
                ('semantic_coherence', models.FloatField(default=0, help_text='Similitud semántica con el tema (0-100)', verbose_name='Coherencia semántica')),
                ('keywords_score', models.FloatField(default=0, help_text='Score basado en palabras clave del tema (0-100)', verbose_name='Puntaje de palabras clave')),
                ('depth_score', models.FloatField(default=0, help_text='Evaluación de profundidad del contenido (0-100)', verbose_name='Puntaje de profundidad')),
                ('coherence_score', models.FloatField(default=0, help_text='Puntaje ponderado de coherencia (0-100)', verbose_name='Nota de coherencia')),
                ('contribution_percentage', models.FloatField(default=0, help_text='Aporte ponderado considerando tiempo y coherencia', verbose_name='Porcentaje de aporte')),
                ('final_grade', models.FloatField(default=0, help_text='Calificación sobre 20', verbose_name='Calificación final')),
                ('coherence_level', models.CharField(default='Regular', help_text='Excelente, Muy Buena, Buena, Regular, Baja, Insuficiente', max_length=20, verbose_name='Nivel de coherencia')),
                ('observations', models.TextField(blank=True, help_text='Retroalimentación automática', verbose_name='Observaciones')),
                ('keywords_found', models.JSONField(blank=True, default=list, verbose_name='Palabras clave encontradas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='presentaciones.presentation', verbose_name='Presentación')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['-final_grade'],
                'unique_together': {('presentation', 'label')},
            },
        ),
    ]
