# Generated by Django 5.2.3 on 2025-10-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0008_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='photo',
            field=models.ImageField(blank=True, help_text='Captura del rostro detectado', null=True, upload_to='participant_photos/', verbose_name='Foto del rostro'),
        ),
    ]
