# Generated by Django 5.2.3 on 2025-10-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0009_participant_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True, verbose_name='Duración en segundos'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='video_fps',
            field=models.FloatField(blank=True, null=True, verbose_name='FPS del video'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='video_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Alto del video'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Miniatura del video'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='video_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ancho del video'),
        ),
    ]
