# Generated by Django 5.2.7 on 2025-10-11 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0010_presentation_duration_seconds_presentation_video_fps_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-ai_grade'], 'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
        migrations.RemoveField(
            model_name='participant',
            name='final_grade',
        ),
        migrations.AddField(
            model_name='participant',
            name='ai_feedback',
            field=models.TextField(blank=True, help_text='Feedback detallado generado por IA (150-250 palabras)', verbose_name='Retroalimentación IA'),
        ),
        migrations.AddField(
            model_name='participant',
            name='ai_grade',
            field=models.FloatField(default=0, help_text='Calificación automática generada por IA (sobre 20)', verbose_name='Calificación IA'),
        ),
        migrations.AddField(
            model_name='participant',
            name='grade_modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AddField(
            model_name='participant',
            name='grade_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_grades', to=settings.AUTH_USER_MODEL, verbose_name='Calificación modificada por'),
        ),
        migrations.AddField(
            model_name='participant',
            name='manual_grade',
            field=models.FloatField(blank=True, help_text='Calificación editada por el profesor (sobre 20)', null=True, verbose_name='Calificación manual'),
        ),
        migrations.AddField(
            model_name='participant',
            name='teacher_feedback',
            field=models.TextField(blank=True, help_text='Comentarios adicionales del profesor', verbose_name='Retroalimentación del profesor'),
        ),
    ]
