# Generated by Django 5.2.7 on 2025-10-12 17:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0011_alter_participant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_model', models.CharField(choices=[('llama-3.3-70b-versatile', 'Llama 3.3 70B (Recomendado)'), ('llama-3.1-70b-versatile', 'Llama 3.1 70B'), ('mixtral-8x7b-32768', 'Mixtral 8x7B')], default='llama-3.3-70b-versatile', max_length=50, verbose_name='Modelo de IA')),
                ('ai_temperature', models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Temperatura del modelo')),
                ('face_detection_confidence', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)], verbose_name='Confianza de detección facial')),
                ('coherence_weight', models.FloatField(default=40.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Peso de coherencia (%)')),
                ('face_detection_weight', models.FloatField(default=20.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Peso de detección facial (%)')),
                ('duration_weight', models.FloatField(default=20.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Peso de duración (%)')),
                ('manual_weight', models.FloatField(default=20.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Peso de calificación manual (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(limit_choices_to={'groups__name': 'Docente'}, on_delete=django.db.models.deletion.CASCADE, related_name='ai_configuration', to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Configuración de IA',
                'verbose_name_plural': 'Configuraciones de IA',
            },
        ),
    ]
