# Generated by Django 5.2.7 on 2025-10-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0012_aiconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, help_text='ID del video almacenado en Cloudinary', max_length=255, null=True, verbose_name='ID público en Cloudinary'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='cloudinary_thumbnail_url',
            field=models.URLField(blank=True, help_text='URL de la miniatura del video en Cloudinary', null=True, verbose_name='URL miniatura Cloudinary'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='cloudinary_url',
            field=models.URLField(blank=True, help_text='URL segura del video en Cloudinary', null=True, verbose_name='URL de Cloudinary'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='is_stored_in_cloud',
            field=models.BooleanField(default=False, help_text='Indica si el video está en Cloudinary', verbose_name='Almacenado en la nube'),
        ),
    ]
