# Generated by Django 5.2.1 on 2025-10-30 02:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0014_participant_time_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfiguration',
            name='strictness_level',
            field=models.CharField(choices=[('strict', 'Estricto'), ('moderate', 'Moderado'), ('lenient', 'Suave')], default='moderate', max_length=20, verbose_name='Nivel de Estrictez'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='max_duration',
            field=models.IntegerField(help_text='Duración máxima en minutos', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Duración máxima (max)'),
        ),
    ]
