# Generated by Django 5.2.1 on 2025-10-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0015_aiconfiguration_strictness_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='strictness_level',
            field=models.CharField(blank=True, choices=[('strict', 'Estricto - Evaluación rigurosa'), ('moderate', 'Moderado - Evaluación balanceada (Recomendado)'), ('lenient', 'Permisivo - Evaluación flexible')], help_text='Nivel de exigencia en la evaluación con IA. Si no se especifica, se usará la configuración global del docente.', max_length=20, null=True, verbose_name='Nivel de Rigurosidad de IA'),
        ),
    ]
