# Generated by Django 5.2.1 on 2025-10-09 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presentaciones', '0004_alter_course_options_alter_presentation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_grade_notifications', models.BooleanField(default=True, verbose_name='Recibir notificaciones de calificaciones')),
                ('receive_assignment_notifications', models.BooleanField(default=True, verbose_name='Recibir notificaciones de asignaciones')),
                ('receive_course_notifications', models.BooleanField(default=True, verbose_name='Recibir notificaciones de cursos')),
                ('receive_system_notifications', models.BooleanField(default=True, verbose_name='Recibir notificaciones del sistema')),
                ('email_notifications', models.BooleanField(default=False, verbose_name='Enviar notificaciones por email')),
                ('digest_frequency', models.CharField(choices=[('NEVER', 'Nunca'), ('DAILY', 'Diario'), ('WEEKLY', 'Semanal')], default='NEVER', max_length=20, verbose_name='Frecuencia de resumen por email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('notification_type', models.CharField(choices=[('PRESENTATION_GRADED', 'Presentación calificada'), ('NEW_ASSIGNMENT', 'Nueva asignación'), ('ASSIGNMENT_DUE_SOON', 'Asignación próxima a vencer'), ('ASSIGNMENT_OVERDUE', 'Asignación vencida'), ('PRESENTATION_ANALYZED', 'Análisis de IA completado'), ('COURSE_UPDATE', 'Actualización de curso'), ('SYSTEM_UPDATE', 'Actualización del sistema'), ('WELCOME', 'Bienvenida')], max_length=30, verbose_name='Tipo de notificación')),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=10, verbose_name='Prioridad')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leída el')),
                ('action_url', models.URLField(blank=True, verbose_name='URL de acción')),
                ('action_text', models.CharField(blank=True, max_length=100, verbose_name='Texto del botón')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha después de la cual la notificación se considerará obsoleta', null=True, verbose_name='Expira el')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('related_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presentaciones.assignment', verbose_name='Asignación relacionada')),
                ('related_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presentaciones.course', verbose_name='Curso relacionado')),
                ('related_presentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presentaciones.presentation', verbose_name='Presentación relacionada')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
