# Generated by Django 5.2.1 on 2025-11-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_action_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PRESENTATION_GRADED', 'Presentación calificada'), ('NEW_ASSIGNMENT', 'Nueva asignación'), ('ASSIGNMENT_DUE_SOON', 'Asignación próxima a vencer'), ('ASSIGNMENT_OVERDUE', 'Asignación vencida'), ('PRESENTATION_ANALYZED', 'Análisis de IA completado'), ('COURSE_UPDATE', 'Actualización de curso'), ('SYSTEM_UPDATE', 'Actualización del sistema'), ('WELCOME', 'Bienvenida'), ('NEW_SUBMISSION', 'Nueva presentación enviada'), ('SUBMISSION_READY_TO_GRADE', 'Presentación lista para calificar'), ('ASSIGNMENT_DEADLINE_APPROACHING', 'Fecha límite de asignación próxima')], max_length=50, verbose_name='Tipo de notificación'),
        ),
    ]
